services:
  # Turath MCP Server
  mcp-server:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.mcp
    container_name: turath-mcp-server
    ports:
      - "8001:8001"
    volumes:
      - ../data/turath_metadata.db:/app/turath_metadata.db:ro
    environment:
      - PYTHONUNBUFFERED=1
      - UV_CACHE_DIR=/tmp/uv-cache
    networks:
      - ai-agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8001/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # FastAPI AI Agent
  ai-agent:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: turath-ai-agent
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - UV_CACHE_DIR=/tmp/uv-cache
      - MCP_SERVER_URL=http://mcp-server:8001/sse
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    networks:
      - ai-agent-network
    depends_on:
      mcp-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  ai-agent-network:
    driver: bridge
    name: ai-agent-network

volumes:
  turath-db:
    driver: local